object Version {
    const val ACTIVITY = "1.5.0"
    const val APPCOMPAT = "1.5.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val CORE = "1.8.0"
    const val COROUTINES = "1.6.1"
    const val ESPRESSO_CORE = "3.4.0"
    const val FRAGMENT = "1.5.0"
    const val GOOGLE = "25.1.0"
    const val JUNIT = "4.13.2"
    const val JUNIT_ANDROID = "1.1.3"
    const val KOIN = "3.1.5"
    const val LIFECYCLE = "2.5.1"
    const val LOTTIE = "4.1.0"
    const val MATERIAL = "1.6.1"
    const val NAVIGATION = "2.5.1"
    const val OKHTTP = "4.9.3"
    const val RETROFIT = "2.9.0"
    const val ROOM = "2.4.3"
    const val WORK_RUNTIME = "2.7.1"
}

object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx:${Version.ACTIVITY}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${Version.APPCOMPAT}"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Version.CONSTRAINT_LAYOUT}"
    const val CONVERTER_GSON = "com.squareup.retrofit2:converter-gson:${Version.RETROFIT}"
    const val CORE_KTX = "androidx.core:core-ktx:${Version.CORE}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.COROUTINES}"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Version.COROUTINES}"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Version.ESPRESSO_CORE}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${Version.FRAGMENT}"
    const val GOOGLE_CLOUD_STORAGE = "com.google.cloud:google-cloud-storage"
    const val GOOGLE_LIBRARIES_BOM = "com.google.cloud:libraries-bom:${Version.GOOGLE}"
    const val GRID_LAYOUT = "androidx.gridlayout:gridlayout"
    const val JUNIT = "junit:junit:${Version.JUNIT}"
    const val JUNIT_ANDROID = "androidx.test.ext:junit:${Version.JUNIT_ANDROID}"
    const val KOIN_ANDROID = "io.insert-koin:koin-android:${Version.KOIN}"
    const val KOIN_ANDROID_COMPAT = "io.insert-koin:koin-android-compat:${Version.KOIN}"
    const val KOIN_TEST = "io.insert-koin:koin-test:${Version.KOIN}"
    const val LIFECYCLE_SERVICE = "androidx.lifecycle:lifecycle-service:${Version.LIFECYCLE}"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.LIFECYCLE}"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${Version.OKHTTP}"
    const val LOTTIE = "com.airbnb.android:lottie:${Version.LOTTIE}"
    const val MATERIAL = "com.google.android.material:material:${Version.MATERIAL}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${Version.NAVIGATION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${Version.NAVIGATION}"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:${Version.OKHTTP}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Version.RETROFIT}"
    const val ROOM_COMPILE = "androidx.room:room-compiler:${Version.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${Version.ROOM}"
    const val ROOM_RUNTIME = "androidx.room:room-runtime:${Version.ROOM}"
    const val ROOM_TESTING = "androidx.room:room-testing:${Version.ROOM}"
    const val WORK_RUNTIME_KTX = "androidx.work:work-runtime-ktx:${Version.WORK_RUNTIME}"
}